# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from packages.protocol.python.worker.v1 import cache_pb2 as worker_dot_v1_dot_cache__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker/v1/cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CacheServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCacheStats = channel.unary_unary(
                '/melix.worker.v1.CacheService/GetCacheStats',
                request_serializer=worker_dot_v1_dot_cache__pb2.GetCacheStatsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.GetCacheStatsResponse.FromString,
                _registered_method=True)
        self.PinPrefix = channel.unary_unary(
                '/melix.worker.v1.CacheService/PinPrefix',
                request_serializer=worker_dot_v1_dot_cache__pb2.PinPrefixRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.PinPrefixResponse.FromString,
                _registered_method=True)
        self.UnpinPrefix = channel.unary_unary(
                '/melix.worker.v1.CacheService/UnpinPrefix',
                request_serializer=worker_dot_v1_dot_cache__pb2.UnpinPrefixRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.UnpinPrefixResponse.FromString,
                _registered_method=True)
        self.SaveBoundarySnapshot = channel.unary_unary(
                '/melix.worker.v1.CacheService/SaveBoundarySnapshot',
                request_serializer=worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotResponse.FromString,
                _registered_method=True)
        self.RestoreBoundarySnapshot = channel.unary_unary(
                '/melix.worker.v1.CacheService/RestoreBoundarySnapshot',
                request_serializer=worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotResponse.FromString,
                _registered_method=True)
        self.PurgeCache = channel.unary_unary(
                '/melix.worker.v1.CacheService/PurgeCache',
                request_serializer=worker_dot_v1_dot_cache__pb2.PurgeCacheRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_cache__pb2.PurgeCacheResponse.FromString,
                _registered_method=True)


class CacheServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCacheStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PinPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnpinPrefix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveBoundarySnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreBoundarySnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.GetCacheStatsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.GetCacheStatsResponse.SerializeToString,
            ),
            'PinPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.PinPrefix,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.PinPrefixRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.PinPrefixResponse.SerializeToString,
            ),
            'UnpinPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.UnpinPrefix,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.UnpinPrefixRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.UnpinPrefixResponse.SerializeToString,
            ),
            'SaveBoundarySnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveBoundarySnapshot,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotResponse.SerializeToString,
            ),
            'RestoreBoundarySnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreBoundarySnapshot,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotResponse.SerializeToString,
            ),
            'PurgeCache': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeCache,
                    request_deserializer=worker_dot_v1_dot_cache__pb2.PurgeCacheRequest.FromString,
                    response_serializer=worker_dot_v1_dot_cache__pb2.PurgeCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'melix.worker.v1.CacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('melix.worker.v1.CacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CacheService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/GetCacheStats',
            worker_dot_v1_dot_cache__pb2.GetCacheStatsRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.GetCacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PinPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/PinPrefix',
            worker_dot_v1_dot_cache__pb2.PinPrefixRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.PinPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnpinPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/UnpinPrefix',
            worker_dot_v1_dot_cache__pb2.UnpinPrefixRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.UnpinPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveBoundarySnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/SaveBoundarySnapshot',
            worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.SaveBoundarySnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreBoundarySnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/RestoreBoundarySnapshot',
            worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.RestoreBoundarySnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.CacheService/PurgeCache',
            worker_dot_v1_dot_cache__pb2.PurgeCacheRequest.SerializeToString,
            worker_dot_v1_dot_cache__pb2.PurgeCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
