# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from packages.protocol.python.worker.v1 import maintenance_pb2 as worker_dot_v1_dot_maintenance__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker/v1/maintenance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MaintenanceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertModel = channel.unary_stream(
                '/melix.worker.v1.MaintenanceService/ConvertModel',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.ConvertModelRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.ConvertModelEvent.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/GetModelInfo',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.RunDoctor = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/RunDoctor',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.RunDoctorRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.RunDoctorResponse.FromString,
                _registered_method=True)
        self.RunBench = channel.unary_stream(
                '/melix.worker.v1.MaintenanceService/RunBench',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.RunBenchRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.RunBenchEvent.FromString,
                _registered_method=True)
        self.RunBenchMatrix = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/RunBenchMatrix',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixResponse.FromString,
                _registered_method=True)
        self.RunEvaluation = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/RunEvaluation',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.RunEvaluationRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.RunEvaluationResponse.FromString,
                _registered_method=True)
        self.ExportResults = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/ExportResults',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.ExportResultsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.ExportResultsResponse.FromString,
                _registered_method=True)
        self.SubmitResults = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/SubmitResults',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.SubmitResultsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.SubmitResultsResponse.FromString,
                _registered_method=True)
        self.SearchHubModels = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/SearchHubModels',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.SearchHubModelsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.SearchHubModelsResponse.FromString,
                _registered_method=True)
        self.GetHubModelCard = channel.unary_unary(
                '/melix.worker.v1.MaintenanceService/GetHubModelCard',
                request_serializer=worker_dot_v1_dot_maintenance__pb2.GetHubModelCardRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_maintenance__pb2.GetHubModelCardResponse.FromString,
                _registered_method=True)


class MaintenanceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunDoctor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBench(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBenchMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHubModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHubModelCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertModel': grpc.unary_stream_rpc_method_handler(
                    servicer.ConvertModel,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.ConvertModelRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.ConvertModelEvent.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.GetModelInfoRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'RunDoctor': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDoctor,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.RunDoctorRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.RunDoctorResponse.SerializeToString,
            ),
            'RunBench': grpc.unary_stream_rpc_method_handler(
                    servicer.RunBench,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.RunBenchRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.RunBenchEvent.SerializeToString,
            ),
            'RunBenchMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBenchMatrix,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixResponse.SerializeToString,
            ),
            'RunEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvaluation,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.RunEvaluationRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.RunEvaluationResponse.SerializeToString,
            ),
            'ExportResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportResults,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.ExportResultsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.ExportResultsResponse.SerializeToString,
            ),
            'SubmitResults': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResults,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.SubmitResultsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.SubmitResultsResponse.SerializeToString,
            ),
            'SearchHubModels': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHubModels,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.SearchHubModelsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.SearchHubModelsResponse.SerializeToString,
            ),
            'GetHubModelCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHubModelCard,
                    request_deserializer=worker_dot_v1_dot_maintenance__pb2.GetHubModelCardRequest.FromString,
                    response_serializer=worker_dot_v1_dot_maintenance__pb2.GetHubModelCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'melix.worker.v1.MaintenanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('melix.worker.v1.MaintenanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MaintenanceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/ConvertModel',
            worker_dot_v1_dot_maintenance__pb2.ConvertModelRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.ConvertModelEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/GetModelInfo',
            worker_dot_v1_dot_maintenance__pb2.GetModelInfoRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunDoctor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/RunDoctor',
            worker_dot_v1_dot_maintenance__pb2.RunDoctorRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.RunDoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBench(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/RunBench',
            worker_dot_v1_dot_maintenance__pb2.RunBenchRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.RunBenchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBenchMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/RunBenchMatrix',
            worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.RunBenchMatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/RunEvaluation',
            worker_dot_v1_dot_maintenance__pb2.RunEvaluationRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.RunEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/ExportResults',
            worker_dot_v1_dot_maintenance__pb2.ExportResultsRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.ExportResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/SubmitResults',
            worker_dot_v1_dot_maintenance__pb2.SubmitResultsRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.SubmitResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHubModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/SearchHubModels',
            worker_dot_v1_dot_maintenance__pb2.SearchHubModelsRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.SearchHubModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHubModelCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.MaintenanceService/GetHubModelCard',
            worker_dot_v1_dot_maintenance__pb2.GetHubModelCardRequest.SerializeToString,
            worker_dot_v1_dot_maintenance__pb2.GetHubModelCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
