# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from packages.protocol.python.worker.v1 import runtime_pb2 as worker_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/Handshake',
                request_serializer=worker_dot_v1_dot_runtime__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/LoadModel',
                request_serializer=worker_dot_v1_dot_runtime__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/UnloadModel',
                request_serializer=worker_dot_v1_dot_runtime__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.WarmupModel = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/WarmupModel',
                request_serializer=worker_dot_v1_dot_runtime__pb2.WarmupModelRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.WarmupModelResponse.FromString,
                _registered_method=True)
        self.GetRuntimeStats = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/GetRuntimeStats',
                request_serializer=worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsResponse.FromString,
                _registered_method=True)
        self.ListLoadedModels = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/ListLoadedModels',
                request_serializer=worker_dot_v1_dot_runtime__pb2.ListLoadedModelsRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.ListLoadedModelsResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/Drain',
                request_serializer=worker_dot_v1_dot_runtime__pb2.DrainRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.DrainResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/melix.worker.v1.RuntimeService/Shutdown',
                request_serializer=worker_dot_v1_dot_runtime__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=worker_dot_v1_dot_runtime__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WarmupModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoadedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.HandshakeRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.HandshakeResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.LoadModelRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.UnloadModelRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.UnloadModelResponse.SerializeToString,
            ),
            'WarmupModel': grpc.unary_unary_rpc_method_handler(
                    servicer.WarmupModel,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.WarmupModelRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.WarmupModelResponse.SerializeToString,
            ),
            'GetRuntimeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeStats,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsResponse.SerializeToString,
            ),
            'ListLoadedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoadedModels,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.ListLoadedModelsRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.ListLoadedModelsResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.DrainRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.DrainResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=worker_dot_v1_dot_runtime__pb2.ShutdownRequest.FromString,
                    response_serializer=worker_dot_v1_dot_runtime__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'melix.worker.v1.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('melix.worker.v1.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/Handshake',
            worker_dot_v1_dot_runtime__pb2.HandshakeRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/LoadModel',
            worker_dot_v1_dot_runtime__pb2.LoadModelRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/UnloadModel',
            worker_dot_v1_dot_runtime__pb2.UnloadModelRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WarmupModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/WarmupModel',
            worker_dot_v1_dot_runtime__pb2.WarmupModelRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.WarmupModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/GetRuntimeStats',
            worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.GetRuntimeStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoadedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/ListLoadedModels',
            worker_dot_v1_dot_runtime__pb2.ListLoadedModelsRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.ListLoadedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/Drain',
            worker_dot_v1_dot_runtime__pb2.DrainRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/melix.worker.v1.RuntimeService/Shutdown',
            worker_dot_v1_dot_runtime__pb2.ShutdownRequest.SerializeToString,
            worker_dot_v1_dot_runtime__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
