// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: worker/v1/cache.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - melix.worker.v1.CacheService

/// Namespace containing generated types for the "melix.worker.v1.CacheService" service.
@available(macOS 15.0, *)
public enum Melix_Worker_V1_CacheService: Sendable {
    /// Service descriptor for the "melix.worker.v1.CacheService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetCacheStats" metadata.
        public enum GetCacheStats: Sendable {
            /// Request type for "GetCacheStats".
            public typealias Input = Melix_Worker_V1_GetCacheStatsRequest
            /// Response type for "GetCacheStats".
            public typealias Output = Melix_Worker_V1_GetCacheStatsResponse
            /// Descriptor for "GetCacheStats".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "GetCacheStats",
                type: .unary
            )
        }
        /// Namespace for "PinPrefix" metadata.
        public enum PinPrefix: Sendable {
            /// Request type for "PinPrefix".
            public typealias Input = Melix_Worker_V1_PinPrefixRequest
            /// Response type for "PinPrefix".
            public typealias Output = Melix_Worker_V1_PinPrefixResponse
            /// Descriptor for "PinPrefix".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "PinPrefix",
                type: .unary
            )
        }
        /// Namespace for "UnpinPrefix" metadata.
        public enum UnpinPrefix: Sendable {
            /// Request type for "UnpinPrefix".
            public typealias Input = Melix_Worker_V1_UnpinPrefixRequest
            /// Response type for "UnpinPrefix".
            public typealias Output = Melix_Worker_V1_UnpinPrefixResponse
            /// Descriptor for "UnpinPrefix".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "UnpinPrefix",
                type: .unary
            )
        }
        /// Namespace for "SaveBoundarySnapshot" metadata.
        public enum SaveBoundarySnapshot: Sendable {
            /// Request type for "SaveBoundarySnapshot".
            public typealias Input = Melix_Worker_V1_SaveBoundarySnapshotRequest
            /// Response type for "SaveBoundarySnapshot".
            public typealias Output = Melix_Worker_V1_SaveBoundarySnapshotResponse
            /// Descriptor for "SaveBoundarySnapshot".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "SaveBoundarySnapshot",
                type: .unary
            )
        }
        /// Namespace for "RestoreBoundarySnapshot" metadata.
        public enum RestoreBoundarySnapshot: Sendable {
            /// Request type for "RestoreBoundarySnapshot".
            public typealias Input = Melix_Worker_V1_RestoreBoundarySnapshotRequest
            /// Response type for "RestoreBoundarySnapshot".
            public typealias Output = Melix_Worker_V1_RestoreBoundarySnapshotResponse
            /// Descriptor for "RestoreBoundarySnapshot".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "RestoreBoundarySnapshot",
                type: .unary
            )
        }
        /// Namespace for "PurgeCache" metadata.
        public enum PurgeCache: Sendable {
            /// Request type for "PurgeCache".
            public typealias Input = Melix_Worker_V1_PurgeCacheRequest
            /// Response type for "PurgeCache".
            public typealias Output = Melix_Worker_V1_PurgeCacheResponse
            /// Descriptor for "PurgeCache".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService"),
                method: "PurgeCache",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "melix.worker.v1.CacheService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetCacheStats.descriptor,
            PinPrefix.descriptor,
            UnpinPrefix.descriptor,
            SaveBoundarySnapshot.descriptor,
            RestoreBoundarySnapshot.descriptor,
            PurgeCache.descriptor
        ]
    }
}

@available(macOS 15.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "melix.worker.v1.CacheService" service.
    public static let melix_worker_v1_CacheService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.CacheService")
}

// MARK: melix.worker.v1.CacheService (server)

@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService {
    /// Streaming variant of the service protocol for the "melix.worker.v1.CacheService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetCacheStats" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_GetCacheStatsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_GetCacheStatsResponse` messages.
        func getCacheStats(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_GetCacheStatsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_GetCacheStatsResponse>

        /// Handle the "PinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_PinPrefixRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_PinPrefixResponse` messages.
        func pinPrefix(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_PinPrefixRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_PinPrefixResponse>

        /// Handle the "UnpinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_UnpinPrefixRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_UnpinPrefixResponse` messages.
        func unpinPrefix(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_UnpinPrefixRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_UnpinPrefixResponse>

        /// Handle the "SaveBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_SaveBoundarySnapshotRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_SaveBoundarySnapshotResponse` messages.
        func saveBoundarySnapshot(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>

        /// Handle the "RestoreBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_RestoreBoundarySnapshotRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_RestoreBoundarySnapshotResponse` messages.
        func restoreBoundarySnapshot(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>

        /// Handle the "PurgeCache" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_PurgeCacheRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_PurgeCacheResponse` messages.
        func purgeCache(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_PurgeCacheRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_PurgeCacheResponse>
    }

    /// Service protocol for the "melix.worker.v1.CacheService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Melix_Worker_V1_CacheService.StreamingServiceProtocol {
        /// Handle the "GetCacheStats" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_GetCacheStatsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_GetCacheStatsResponse` message.
        func getCacheStats(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_GetCacheStatsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_GetCacheStatsResponse>

        /// Handle the "PinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PinPrefixRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_PinPrefixResponse` message.
        func pinPrefix(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_PinPrefixRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_PinPrefixResponse>

        /// Handle the "UnpinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_UnpinPrefixRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_UnpinPrefixResponse` message.
        func unpinPrefix(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_UnpinPrefixRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_UnpinPrefixResponse>

        /// Handle the "SaveBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_SaveBoundarySnapshotRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_SaveBoundarySnapshotResponse` message.
        func saveBoundarySnapshot(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>

        /// Handle the "RestoreBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_RestoreBoundarySnapshotRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_RestoreBoundarySnapshotResponse` message.
        func restoreBoundarySnapshot(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>

        /// Handle the "PurgeCache" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PurgeCacheRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_PurgeCacheResponse` message.
        func purgeCache(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_PurgeCacheRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_PurgeCacheResponse>
    }

    /// Simple service protocol for the "melix.worker.v1.CacheService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Melix_Worker_V1_CacheService.ServiceProtocol {
        /// Handle the "GetCacheStats" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_GetCacheStatsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_GetCacheStatsResponse` to respond with.
        func getCacheStats(
            request: Melix_Worker_V1_GetCacheStatsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_GetCacheStatsResponse

        /// Handle the "PinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_PinPrefixRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_PinPrefixResponse` to respond with.
        func pinPrefix(
            request: Melix_Worker_V1_PinPrefixRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_PinPrefixResponse

        /// Handle the "UnpinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_UnpinPrefixRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_UnpinPrefixResponse` to respond with.
        func unpinPrefix(
            request: Melix_Worker_V1_UnpinPrefixRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_UnpinPrefixResponse

        /// Handle the "SaveBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_SaveBoundarySnapshotRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_SaveBoundarySnapshotResponse` to respond with.
        func saveBoundarySnapshot(
            request: Melix_Worker_V1_SaveBoundarySnapshotRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_SaveBoundarySnapshotResponse

        /// Handle the "RestoreBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_RestoreBoundarySnapshotRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_RestoreBoundarySnapshotResponse` to respond with.
        func restoreBoundarySnapshot(
            request: Melix_Worker_V1_RestoreBoundarySnapshotRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_RestoreBoundarySnapshotResponse

        /// Handle the "PurgeCache" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_PurgeCacheRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_PurgeCacheResponse` to respond with.
        func purgeCache(
            request: Melix_Worker_V1_PurgeCacheRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_PurgeCacheResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.GetCacheStats.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_GetCacheStatsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_GetCacheStatsResponse>(),
            handler: { request, context in
                try await self.getCacheStats(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.PinPrefix.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_PinPrefixRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_PinPrefixResponse>(),
            handler: { request, context in
                try await self.pinPrefix(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.UnpinPrefix.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_UnpinPrefixRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_UnpinPrefixResponse>(),
            handler: { request, context in
                try await self.unpinPrefix(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.SaveBoundarySnapshot.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_SaveBoundarySnapshotRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_SaveBoundarySnapshotResponse>(),
            handler: { request, context in
                try await self.saveBoundarySnapshot(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.RestoreBoundarySnapshot.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_RestoreBoundarySnapshotRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_RestoreBoundarySnapshotResponse>(),
            handler: { request, context in
                try await self.restoreBoundarySnapshot(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_CacheService.Method.PurgeCache.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_PurgeCacheRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_PurgeCacheResponse>(),
            handler: { request, context in
                try await self.purgeCache(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService.ServiceProtocol {
    public func getCacheStats(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_GetCacheStatsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_GetCacheStatsResponse> {
        let response = try await self.getCacheStats(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func pinPrefix(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_PinPrefixRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_PinPrefixResponse> {
        let response = try await self.pinPrefix(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func unpinPrefix(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_UnpinPrefixRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_UnpinPrefixResponse> {
        let response = try await self.unpinPrefix(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func saveBoundarySnapshot(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse> {
        let response = try await self.saveBoundarySnapshot(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func restoreBoundarySnapshot(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse> {
        let response = try await self.restoreBoundarySnapshot(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func purgeCache(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_PurgeCacheRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_PurgeCacheResponse> {
        let response = try await self.purgeCache(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService.SimpleServiceProtocol {
    public func getCacheStats(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_GetCacheStatsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_GetCacheStatsResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_GetCacheStatsResponse>(
            message: try await self.getCacheStats(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func pinPrefix(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_PinPrefixRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_PinPrefixResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_PinPrefixResponse>(
            message: try await self.pinPrefix(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func unpinPrefix(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_UnpinPrefixRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_UnpinPrefixResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_UnpinPrefixResponse>(
            message: try await self.unpinPrefix(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func saveBoundarySnapshot(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>(
            message: try await self.saveBoundarySnapshot(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func restoreBoundarySnapshot(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>(
            message: try await self.restoreBoundarySnapshot(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func purgeCache(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_PurgeCacheRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_PurgeCacheResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_PurgeCacheResponse>(
            message: try await self.purgeCache(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: melix.worker.v1.CacheService (client)

@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService {
    /// Generated client protocol for the "melix.worker.v1.CacheService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetCacheStats" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_GetCacheStatsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_GetCacheStatsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_GetCacheStatsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getCacheStats<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_GetCacheStatsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_GetCacheStatsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_GetCacheStatsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_GetCacheStatsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PinPrefixRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_PinPrefixRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_PinPrefixResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func pinPrefix<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_PinPrefixRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_PinPrefixRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_PinPrefixResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PinPrefixResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UnpinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_UnpinPrefixRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_UnpinPrefixRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_UnpinPrefixResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func unpinPrefix<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_UnpinPrefixRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_UnpinPrefixRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_UnpinPrefixResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_UnpinPrefixResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SaveBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_SaveBoundarySnapshotRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_SaveBoundarySnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_SaveBoundarySnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func saveBoundarySnapshot<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_SaveBoundarySnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RestoreBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_RestoreBoundarySnapshotRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_RestoreBoundarySnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_RestoreBoundarySnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func restoreBoundarySnapshot<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_RestoreBoundarySnapshotResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PurgeCache" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PurgeCacheRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_PurgeCacheRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_PurgeCacheResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func purgeCache<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_PurgeCacheRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_PurgeCacheRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_PurgeCacheResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PurgeCacheResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "melix.worker.v1.CacheService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetCacheStats" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_GetCacheStatsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_GetCacheStatsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_GetCacheStatsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getCacheStats<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_GetCacheStatsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_GetCacheStatsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_GetCacheStatsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_GetCacheStatsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.GetCacheStats.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PinPrefixRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_PinPrefixRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_PinPrefixResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func pinPrefix<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_PinPrefixRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_PinPrefixRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_PinPrefixResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PinPrefixResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.PinPrefix.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UnpinPrefix" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_UnpinPrefixRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_UnpinPrefixRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_UnpinPrefixResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func unpinPrefix<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_UnpinPrefixRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_UnpinPrefixRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_UnpinPrefixResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_UnpinPrefixResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.UnpinPrefix.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SaveBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_SaveBoundarySnapshotRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_SaveBoundarySnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_SaveBoundarySnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func saveBoundarySnapshot<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_SaveBoundarySnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.SaveBoundarySnapshot.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RestoreBoundarySnapshot" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_RestoreBoundarySnapshotRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_RestoreBoundarySnapshotRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_RestoreBoundarySnapshotResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func restoreBoundarySnapshot<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_RestoreBoundarySnapshotResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.RestoreBoundarySnapshot.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "PurgeCache" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_PurgeCacheRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_PurgeCacheRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_PurgeCacheResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func purgeCache<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_PurgeCacheRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_PurgeCacheRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_PurgeCacheResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PurgeCacheResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_CacheService.Method.PurgeCache.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService.ClientProtocol {
    /// Call the "GetCacheStats" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_GetCacheStatsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getCacheStats<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_GetCacheStatsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_GetCacheStatsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getCacheStats(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_GetCacheStatsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_GetCacheStatsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PinPrefix" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_PinPrefixRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pinPrefix<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_PinPrefixRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PinPrefixResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.pinPrefix(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_PinPrefixRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_PinPrefixResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnpinPrefix" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_UnpinPrefixRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unpinPrefix<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_UnpinPrefixRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_UnpinPrefixResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unpinPrefix(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_UnpinPrefixRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_UnpinPrefixResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SaveBoundarySnapshot" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_SaveBoundarySnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func saveBoundarySnapshot<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.saveBoundarySnapshot(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_SaveBoundarySnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_SaveBoundarySnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RestoreBoundarySnapshot" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_RestoreBoundarySnapshotRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func restoreBoundarySnapshot<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.restoreBoundarySnapshot(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_RestoreBoundarySnapshotRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_RestoreBoundarySnapshotResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PurgeCache" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_PurgeCacheRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func purgeCache<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_PurgeCacheRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PurgeCacheResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.purgeCache(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_PurgeCacheRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_PurgeCacheResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, *)
extension Melix_Worker_V1_CacheService.ClientProtocol {
    /// Call the "GetCacheStats" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getCacheStats<Result>(
        _ message: Melix_Worker_V1_GetCacheStatsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_GetCacheStatsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_GetCacheStatsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getCacheStats(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PinPrefix" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func pinPrefix<Result>(
        _ message: Melix_Worker_V1_PinPrefixRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PinPrefixResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_PinPrefixRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.pinPrefix(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnpinPrefix" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unpinPrefix<Result>(
        _ message: Melix_Worker_V1_UnpinPrefixRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_UnpinPrefixResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_UnpinPrefixRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.unpinPrefix(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SaveBoundarySnapshot" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func saveBoundarySnapshot<Result>(
        _ message: Melix_Worker_V1_SaveBoundarySnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_SaveBoundarySnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_SaveBoundarySnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.saveBoundarySnapshot(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RestoreBoundarySnapshot" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func restoreBoundarySnapshot<Result>(
        _ message: Melix_Worker_V1_RestoreBoundarySnapshotRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_RestoreBoundarySnapshotResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_RestoreBoundarySnapshotRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.restoreBoundarySnapshot(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "PurgeCache" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func purgeCache<Result>(
        _ message: Melix_Worker_V1_PurgeCacheRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_PurgeCacheResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_PurgeCacheRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.purgeCache(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}