// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: worker/v1/cache.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Melix_Worker_V1_CacheStats: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var l1Bytes: UInt64 = 0

  public var l2Bytes: UInt64 = 0

  public var blockCount: UInt64 = 0

  public var pinnedPrefixCount: UInt64 = 0

  public var snapshotCount: UInt64 = 0

  public var l1HitRate: Double = 0

  public var l2HitRate: Double = 0

  public var dedupRatio: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_GetCacheStatsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_GetCacheStatsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var stats: Melix_Worker_V1_CacheStats {
    get {_stats ?? Melix_Worker_V1_CacheStats()}
    set {_stats = newValue}
  }
  /// Returns true if `stats` has been explicitly set.
  public var hasStats: Bool {self._stats != nil}
  /// Clears the value of `stats`. Subsequent reads from it will return its default value.
  public mutating func clearStats() {self._stats = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _stats: Melix_Worker_V1_CacheStats? = nil
}

public struct Melix_Worker_V1_PrefixRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var prefixID: String = String()

  public var scope: Melix_Worker_V1_CacheScope {
    get {_scope ?? Melix_Worker_V1_CacheScope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {self._scope = nil}

  public var cacheKey: Melix_Worker_V1_CacheKey {
    get {_cacheKey ?? Melix_Worker_V1_CacheKey()}
    set {_cacheKey = newValue}
  }
  /// Returns true if `cacheKey` has been explicitly set.
  public var hasCacheKey: Bool {self._cacheKey != nil}
  /// Clears the value of `cacheKey`. Subsequent reads from it will return its default value.
  public mutating func clearCacheKey() {self._cacheKey = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _scope: Melix_Worker_V1_CacheScope? = nil
  fileprivate var _cacheKey: Melix_Worker_V1_CacheKey? = nil
}

public struct Melix_Worker_V1_PinPrefixRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var prefix: Melix_Worker_V1_PrefixRef {
    get {_prefix ?? Melix_Worker_V1_PrefixRef()}
    set {_prefix = newValue}
  }
  /// Returns true if `prefix` has been explicitly set.
  public var hasPrefix: Bool {self._prefix != nil}
  /// Clears the value of `prefix`. Subsequent reads from it will return its default value.
  public mutating func clearPrefix() {self._prefix = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _prefix: Melix_Worker_V1_PrefixRef? = nil
}

public struct Melix_Worker_V1_PinPrefixResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var error: Melix_Worker_V1_ErrorStatus {
    get {_error ?? Melix_Worker_V1_ErrorStatus()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Melix_Worker_V1_ErrorStatus? = nil
}

public struct Melix_Worker_V1_UnpinPrefixRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var prefix: Melix_Worker_V1_PrefixRef {
    get {_prefix ?? Melix_Worker_V1_PrefixRef()}
    set {_prefix = newValue}
  }
  /// Returns true if `prefix` has been explicitly set.
  public var hasPrefix: Bool {self._prefix != nil}
  /// Clears the value of `prefix`. Subsequent reads from it will return its default value.
  public mutating func clearPrefix() {self._prefix = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _prefix: Melix_Worker_V1_PrefixRef? = nil
}

public struct Melix_Worker_V1_UnpinPrefixResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var error: Melix_Worker_V1_ErrorStatus {
    get {_error ?? Melix_Worker_V1_ErrorStatus()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Melix_Worker_V1_ErrorStatus? = nil
}

public struct Melix_Worker_V1_SaveBoundarySnapshotRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var decodeHandle: String = String()

  public var tokenBoundary: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_SaveBoundarySnapshotResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var error: Melix_Worker_V1_ErrorStatus {
    get {_error ?? Melix_Worker_V1_ErrorStatus()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var snapshotID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Melix_Worker_V1_ErrorStatus? = nil
}

public struct Melix_Worker_V1_RestoreBoundarySnapshotRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var snapshotID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_RestoreBoundarySnapshotResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var error: Melix_Worker_V1_ErrorStatus {
    get {_error ?? Melix_Worker_V1_ErrorStatus()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var decodeHandle: String = String()

  public var blockTableID: String = String()

  public var blockTable: Melix_Worker_V1_BlockTable {
    get {_blockTable ?? Melix_Worker_V1_BlockTable()}
    set {_blockTable = newValue}
  }
  /// Returns true if `blockTable` has been explicitly set.
  public var hasBlockTable: Bool {self._blockTable != nil}
  /// Clears the value of `blockTable`. Subsequent reads from it will return its default value.
  public mutating func clearBlockTable() {self._blockTable = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Melix_Worker_V1_ErrorStatus? = nil
  fileprivate var _blockTable: Melix_Worker_V1_BlockTable? = nil
}

public struct Melix_Worker_V1_PurgeCacheRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scope: Melix_Worker_V1_CacheScope {
    get {_scope ?? Melix_Worker_V1_CacheScope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {self._scope = nil}

  public var cacheKey: Melix_Worker_V1_CacheKey {
    get {_cacheKey ?? Melix_Worker_V1_CacheKey()}
    set {_cacheKey = newValue}
  }
  /// Returns true if `cacheKey` has been explicitly set.
  public var hasCacheKey: Bool {self._cacheKey != nil}
  /// Clears the value of `cacheKey`. Subsequent reads from it will return its default value.
  public mutating func clearCacheKey() {self._cacheKey = nil}

  public var tier: String = String()

  public var includePinned: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _scope: Melix_Worker_V1_CacheScope? = nil
  fileprivate var _cacheKey: Melix_Worker_V1_CacheKey? = nil
}

public struct Melix_Worker_V1_PurgeCacheResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ok: Bool = false

  public var error: Melix_Worker_V1_ErrorStatus {
    get {_error ?? Melix_Worker_V1_ErrorStatus()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var purgedBlocks: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Melix_Worker_V1_ErrorStatus? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "melix.worker.v1"

extension Melix_Worker_V1_CacheStats: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CacheStats"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}l1_bytes\0\u{3}l2_bytes\0\u{3}block_count\0\u{3}pinned_prefix_count\0\u{3}snapshot_count\0\u{3}l1_hit_rate\0\u{3}l2_hit_rate\0\u{3}dedup_ratio\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.l1Bytes) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.l2Bytes) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.blockCount) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.pinnedPrefixCount) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.snapshotCount) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.l1HitRate) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.l2HitRate) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.dedupRatio) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.l1Bytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.l1Bytes, fieldNumber: 1)
    }
    if self.l2Bytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.l2Bytes, fieldNumber: 2)
    }
    if self.blockCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.blockCount, fieldNumber: 3)
    }
    if self.pinnedPrefixCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.pinnedPrefixCount, fieldNumber: 4)
    }
    if self.snapshotCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.snapshotCount, fieldNumber: 5)
    }
    if self.l1HitRate.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.l1HitRate, fieldNumber: 6)
    }
    if self.l2HitRate.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.l2HitRate, fieldNumber: 7)
    }
    if self.dedupRatio.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.dedupRatio, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_CacheStats, rhs: Melix_Worker_V1_CacheStats) -> Bool {
    if lhs.l1Bytes != rhs.l1Bytes {return false}
    if lhs.l2Bytes != rhs.l2Bytes {return false}
    if lhs.blockCount != rhs.blockCount {return false}
    if lhs.pinnedPrefixCount != rhs.pinnedPrefixCount {return false}
    if lhs.snapshotCount != rhs.snapshotCount {return false}
    if lhs.l1HitRate != rhs.l1HitRate {return false}
    if lhs.l2HitRate != rhs.l2HitRate {return false}
    if lhs.dedupRatio != rhs.dedupRatio {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_GetCacheStatsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetCacheStatsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_GetCacheStatsRequest, rhs: Melix_Worker_V1_GetCacheStatsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_GetCacheStatsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetCacheStatsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}stats\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._stats) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._stats {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_GetCacheStatsResponse, rhs: Melix_Worker_V1_GetCacheStatsResponse) -> Bool {
    if lhs._stats != rhs._stats {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PrefixRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrefixRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prefix_id\0\u{1}scope\0\u{3}cache_key\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.prefixID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._cacheKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.prefixID.isEmpty {
      try visitor.visitSingularStringField(value: self.prefixID, fieldNumber: 1)
    }
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._cacheKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PrefixRef, rhs: Melix_Worker_V1_PrefixRef) -> Bool {
    if lhs.prefixID != rhs.prefixID {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs._cacheKey != rhs._cacheKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PinPrefixRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PinPrefixRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prefix\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._prefix) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._prefix {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PinPrefixRequest, rhs: Melix_Worker_V1_PinPrefixRequest) -> Bool {
    if lhs._prefix != rhs._prefix {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PinPrefixResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PinPrefixResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PinPrefixResponse, rhs: Melix_Worker_V1_PinPrefixResponse) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_UnpinPrefixRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnpinPrefixRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prefix\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._prefix) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._prefix {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_UnpinPrefixRequest, rhs: Melix_Worker_V1_UnpinPrefixRequest) -> Bool {
    if lhs._prefix != rhs._prefix {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_UnpinPrefixResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UnpinPrefixResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_UnpinPrefixResponse, rhs: Melix_Worker_V1_UnpinPrefixResponse) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_SaveBoundarySnapshotRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SaveBoundarySnapshotRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}decode_handle\0\u{3}token_boundary\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.decodeHandle) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.tokenBoundary) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.decodeHandle.isEmpty {
      try visitor.visitSingularStringField(value: self.decodeHandle, fieldNumber: 2)
    }
    if self.tokenBoundary != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenBoundary, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_SaveBoundarySnapshotRequest, rhs: Melix_Worker_V1_SaveBoundarySnapshotRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.decodeHandle != rhs.decodeHandle {return false}
    if lhs.tokenBoundary != rhs.tokenBoundary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_SaveBoundarySnapshotResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SaveBoundarySnapshotResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}error\0\u{3}snapshot_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.snapshotID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.snapshotID.isEmpty {
      try visitor.visitSingularStringField(value: self.snapshotID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_SaveBoundarySnapshotResponse, rhs: Melix_Worker_V1_SaveBoundarySnapshotResponse) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs._error != rhs._error {return false}
    if lhs.snapshotID != rhs.snapshotID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_RestoreBoundarySnapshotRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RestoreBoundarySnapshotRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}snapshot_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.snapshotID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.snapshotID.isEmpty {
      try visitor.visitSingularStringField(value: self.snapshotID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_RestoreBoundarySnapshotRequest, rhs: Melix_Worker_V1_RestoreBoundarySnapshotRequest) -> Bool {
    if lhs.snapshotID != rhs.snapshotID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_RestoreBoundarySnapshotResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RestoreBoundarySnapshotResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}error\0\u{3}decode_handle\0\u{3}block_table_id\0\u{3}block_table\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.decodeHandle) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.blockTableID) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._blockTable) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.decodeHandle.isEmpty {
      try visitor.visitSingularStringField(value: self.decodeHandle, fieldNumber: 3)
    }
    if !self.blockTableID.isEmpty {
      try visitor.visitSingularStringField(value: self.blockTableID, fieldNumber: 4)
    }
    try { if let v = self._blockTable {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_RestoreBoundarySnapshotResponse, rhs: Melix_Worker_V1_RestoreBoundarySnapshotResponse) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs._error != rhs._error {return false}
    if lhs.decodeHandle != rhs.decodeHandle {return false}
    if lhs.blockTableID != rhs.blockTableID {return false}
    if lhs._blockTable != rhs._blockTable {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PurgeCacheRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PurgeCacheRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}scope\0\u{3}cache_key\0\u{1}tier\0\u{3}include_pinned\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._cacheKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.tier) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.includePinned) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._cacheKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.tier.isEmpty {
      try visitor.visitSingularStringField(value: self.tier, fieldNumber: 3)
    }
    if self.includePinned != false {
      try visitor.visitSingularBoolField(value: self.includePinned, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PurgeCacheRequest, rhs: Melix_Worker_V1_PurgeCacheRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._cacheKey != rhs._cacheKey {return false}
    if lhs.tier != rhs.tier {return false}
    if lhs.includePinned != rhs.includePinned {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PurgeCacheResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PurgeCacheResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}error\0\u{3}purged_blocks\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.purgedBlocks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 1)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.purgedBlocks != 0 {
      try visitor.visitSingularUInt64Field(value: self.purgedBlocks, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PurgeCacheResponse, rhs: Melix_Worker_V1_PurgeCacheResponse) -> Bool {
    if lhs.ok != rhs.ok {return false}
    if lhs._error != rhs._error {return false}
    if lhs.purgedBlocks != rhs.purgedBlocks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
