// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: worker/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Melix_Worker_V1_AdmissionState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case admissionQueued // = 1
  case admissionAdmitted // = 2
  case admissionRejected // = 3
  case admissionDropped // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .admissionQueued
    case 2: self = .admissionAdmitted
    case 3: self = .admissionRejected
    case 4: self = .admissionDropped
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .admissionQueued: return 1
    case .admissionAdmitted: return 2
    case .admissionRejected: return 3
    case .admissionDropped: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Melix_Worker_V1_AdmissionState] = [
    .unspecified,
    .admissionQueued,
    .admissionAdmitted,
    .admissionRejected,
    .admissionDropped,
  ]

}

public enum Melix_Worker_V1_ExecutionPhase: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case executionQueued // = 1
  case executionAdmitted // = 2
  case executionPrefilling // = 3
  case executionDecoding // = 4
  case executionCompleted // = 5
  case executionAborted // = 6
  case executionFailed // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .executionQueued
    case 2: self = .executionAdmitted
    case 3: self = .executionPrefilling
    case 4: self = .executionDecoding
    case 5: self = .executionCompleted
    case 6: self = .executionAborted
    case 7: self = .executionFailed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .executionQueued: return 1
    case .executionAdmitted: return 2
    case .executionPrefilling: return 3
    case .executionDecoding: return 4
    case .executionCompleted: return 5
    case .executionAborted: return 6
    case .executionFailed: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Melix_Worker_V1_ExecutionPhase] = [
    .unspecified,
    .executionQueued,
    .executionAdmitted,
    .executionPrefilling,
    .executionDecoding,
    .executionCompleted,
    .executionAborted,
    .executionFailed,
  ]

}

public enum Melix_Worker_V1_AccelerationMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case baseline // = 1
  case speculativeDecode // = 2
  case acceleratedPrefill // = 3
  case activeKvQuantized // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .baseline
    case 2: self = .speculativeDecode
    case 3: self = .acceleratedPrefill
    case 4: self = .activeKvQuantized
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .baseline: return 1
    case .speculativeDecode: return 2
    case .acceleratedPrefill: return 3
    case .activeKvQuantized: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Melix_Worker_V1_AccelerationMode] = [
    .unspecified,
    .baseline,
    .speculativeDecode,
    .acceleratedPrefill,
    .activeKvQuantized,
  ]

}

public struct Melix_Worker_V1_ErrorStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: String = String()

  public var message: String = String()

  public var retriable: Bool = false

  public var details: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ModelSpec: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var modelID: String = String()

  public var modelPath: String = String()

  public var modelKind: String = String()

  public var revision: String = String()

  public var tokenizerHash: String = String()

  public var quantProfileID: String = String()

  public var parserMode: String = String()

  public var reasoningMode: String = String()

  public var maxContext: UInt32 = 0

  public var ext: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_RuntimeCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var cache: Melix_Worker_V1_CacheCapabilities {
    get {_cache ?? Melix_Worker_V1_CacheCapabilities()}
    set {_cache = newValue}
  }
  /// Returns true if `cache` has been explicitly set.
  public var hasCache: Bool {self._cache != nil}
  /// Clears the value of `cache`. Subsequent reads from it will return its default value.
  public mutating func clearCache() {self._cache = nil}

  public var execution: Melix_Worker_V1_ExecutionCapabilities {
    get {_execution ?? Melix_Worker_V1_ExecutionCapabilities()}
    set {_execution = newValue}
  }
  /// Returns true if `execution` has been explicitly set.
  public var hasExecution: Bool {self._execution != nil}
  /// Clears the value of `execution`. Subsequent reads from it will return its default value.
  public mutating func clearExecution() {self._execution = nil}

  public var parsing: Melix_Worker_V1_ParserCapabilities {
    get {_parsing ?? Melix_Worker_V1_ParserCapabilities()}
    set {_parsing = newValue}
  }
  /// Returns true if `parsing` has been explicitly set.
  public var hasParsing: Bool {self._parsing != nil}
  /// Clears the value of `parsing`. Subsequent reads from it will return its default value.
  public mutating func clearParsing() {self._parsing = nil}

  public var multimodal: Melix_Worker_V1_MultimodalCapabilities {
    get {_multimodal ?? Melix_Worker_V1_MultimodalCapabilities()}
    set {_multimodal = newValue}
  }
  /// Returns true if `multimodal` has been explicitly set.
  public var hasMultimodal: Bool {self._multimodal != nil}
  /// Clears the value of `multimodal`. Subsequent reads from it will return its default value.
  public mutating func clearMultimodal() {self._multimodal = nil}

  public var ext: [Melix_Worker_V1_Capability] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cache: Melix_Worker_V1_CacheCapabilities? = nil
  fileprivate var _execution: Melix_Worker_V1_ExecutionCapabilities? = nil
  fileprivate var _parsing: Melix_Worker_V1_ParserCapabilities? = nil
  fileprivate var _multimodal: Melix_Worker_V1_MultimodalCapabilities? = nil
}

public struct Melix_Worker_V1_CacheCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportsPrefixCache: Bool = false

  public var supportsPagedCache: Bool = false

  public var supportsDiskCache: Bool = false

  public var kvQuantProfiles: [String] = []

  public var supportsBoundarySnapshots: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ExecutionCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportsContinuousBatching: Bool = false

  public var supportsSpeculativeDecoding: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ParserCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportsToolCallAutoParsing: Bool = false

  public var supportsReasoningSeparation: Bool = false

  public var supportedToolParsers: [String] = []

  public var supportedReasoningParsers: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_MultimodalCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var supportsVision: Bool = false

  public var supportsAudio: Bool = false

  public var supportsImageGeneration: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_Capability: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var metadata: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_CacheScope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var modelID: String = String()

  public var revision: String = String()

  public var tokenizerHash: String = String()

  public var quantProfileID: String = String()

  public var promptTemplateHash: String = String()

  public var parserMode: String = String()

  public var reasoningMode: String = String()

  public var multimodalAdapterHash: String = String()

  public var scopeID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_CacheKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var prefixHash: Data = Data()

  public var fingerprintHash: Data = Data()

  public var scopeID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_PrefixRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var prefixID: String = String()

  public var cacheKey: Melix_Worker_V1_CacheKey {
    get {_cacheKey ?? Melix_Worker_V1_CacheKey()}
    set {_cacheKey = newValue}
  }
  /// Returns true if `cacheKey` has been explicitly set.
  public var hasCacheKey: Bool {self._cacheKey != nil}
  /// Clears the value of `cacheKey`. Subsequent reads from it will return its default value.
  public mutating func clearCacheKey() {self._cacheKey = nil}

  public var scope: Melix_Worker_V1_CacheScope {
    get {_scope ?? Melix_Worker_V1_CacheScope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  public var hasScope: Bool {self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  public mutating func clearScope() {self._scope = nil}

  public var tokenLength: UInt32 = 0

  public var pinned: Bool = false

  public var tier: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cacheKey: Melix_Worker_V1_CacheKey? = nil
  fileprivate var _scope: Melix_Worker_V1_CacheScope? = nil
}

public struct Melix_Worker_V1_SnapshotRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var snapshotID: String = String()

  public var requestID: String = String()

  public var sessionID: String = String()

  public var branchID: String = String()

  public var tokenBoundary: UInt32 = 0

  public var checkpointID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_SamplingConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var temperature: Float = 0

  public var topP: Float = 0

  public var topK: UInt32 = 0

  public var frequencyPenalty: Float = 0

  public var presencePenalty: Float = 0

  public var maxOutputTokens: UInt32 = 0

  public var stop: [String] = []

  public var seed: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ReasoningConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enabled: Bool = false

  public var parser: String = String()

  public var separateStream: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ToolDefinition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var description_p: String = String()

  public var jsonSchema: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_ToolConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var tools: [Melix_Worker_V1_ToolDefinition] = []

  public var schemaFormat: String = String()

  public var schemaVersion: String = String()

  public var toolsetVersion: String = String()

  public var parser: String = String()

  public var parserContractVersion: String = String()

  public var toolChoice: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_MessagePart: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var part: Melix_Worker_V1_MessagePart.OneOf_Part? = nil

  public var text: String {
    get {
      if case .text(let v)? = part {return v}
      return String()
    }
    set {part = .text(newValue)}
  }

  public var imageUri: String {
    get {
      if case .imageUri(let v)? = part {return v}
      return String()
    }
    set {part = .imageUri(newValue)}
  }

  public var imageBytes: Data {
    get {
      if case .imageBytes(let v)? = part {return v}
      return Data()
    }
    set {part = .imageBytes(newValue)}
  }

  public var audioUri: String {
    get {
      if case .audioUri(let v)? = part {return v}
      return String()
    }
    set {part = .audioUri(newValue)}
  }

  public var audioBytes: Data {
    get {
      if case .audioBytes(let v)? = part {return v}
      return Data()
    }
    set {part = .audioBytes(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Part: Equatable, Sendable {
    case text(String)
    case imageUri(String)
    case imageBytes(Data)
    case audioUri(String)
    case audioBytes(Data)

  }

  public init() {}
}

public struct Melix_Worker_V1_ChatMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var role: String = String()

  public var name: String = String()

  public var parts: [Melix_Worker_V1_MessagePart] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_CacheHints: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var allowL1: Bool = false

  public var allowL2: Bool = false

  public var persistL2: Bool = false

  public var preferHotPrefix: Bool = false

  public var saveBoundarySnapshot: Bool = false

  public var restoreSnapshotID: String = String()

  public var pinPrefixIds: [String] = []

  public var cachePolicy: String = String()

  public var preferredBlockSize: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_RequestIdentity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var sessionID: String = String()

  public var branchID: String = String()

  public var parentRequestID: String = String()

  public var workflowRunID: String = String()

  public var workflowNodeID: String = String()

  public var latencyClass: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_SchedulingHints: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var priority: Int32 = 0

  public var lane: String = String()

  public var latencySensitive: Bool = false

  public var queueDelayMs: UInt32 = 0

  public var queuePosition: UInt32 = 0

  public var admissionPolicy: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_AccelerationPolicy: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mode: Melix_Worker_V1_AccelerationMode = .unspecified

  public var profileID: String = String()

  public var draftModelID: String = String()

  public var prefillHint: String = String()

  public var activeKvQuantProfile: String = String()

  public var allowBaselineFallback: Bool = false

  public var ext: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Melix_Worker_V1_BlockTable: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var blocks: [Melix_Worker_V1_BlockRef] = []

  public var cacheKey: Melix_Worker_V1_CacheKey {
    get {_cacheKey ?? Melix_Worker_V1_CacheKey()}
    set {_cacheKey = newValue}
  }
  /// Returns true if `cacheKey` has been explicitly set.
  public var hasCacheKey: Bool {self._cacheKey != nil}
  /// Clears the value of `cacheKey`. Subsequent reads from it will return its default value.
  public mutating func clearCacheKey() {self._cacheKey = nil}

  public var scopeID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _cacheKey: Melix_Worker_V1_CacheKey? = nil
}

public struct Melix_Worker_V1_BlockRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var blockID: String = String()

  public var tokenStart: Int32 = 0

  public var tokenEnd: Int32 = 0

  public var bytes: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "melix.worker.v1"

extension Melix_Worker_V1_AdmissionState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ADMISSION_STATE_UNSPECIFIED\0\u{1}ADMISSION_QUEUED\0\u{1}ADMISSION_ADMITTED\0\u{1}ADMISSION_REJECTED\0\u{1}ADMISSION_DROPPED\0")
}

extension Melix_Worker_V1_ExecutionPhase: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0EXECUTION_PHASE_UNSPECIFIED\0\u{1}EXECUTION_QUEUED\0\u{1}EXECUTION_ADMITTED\0\u{1}EXECUTION_PREFILLING\0\u{1}EXECUTION_DECODING\0\u{1}EXECUTION_COMPLETED\0\u{1}EXECUTION_ABORTED\0\u{1}EXECUTION_FAILED\0")
}

extension Melix_Worker_V1_AccelerationMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ACCELERATION_MODE_UNSPECIFIED\0\u{1}ACCELERATION_MODE_BASELINE\0\u{1}ACCELERATION_MODE_SPECULATIVE_DECODE\0\u{1}ACCELERATION_MODE_ACCELERATED_PREFILL\0\u{1}ACCELERATION_MODE_ACTIVE_KV_QUANTIZED\0")
}

extension Melix_Worker_V1_ErrorStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ErrorStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}retriable\0\u{1}details\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.retriable) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.details) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.retriable != false {
      try visitor.visitSingularBoolField(value: self.retriable, fieldNumber: 3)
    }
    if !self.details.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.details, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ErrorStatus, rhs: Melix_Worker_V1_ErrorStatus) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.retriable != rhs.retriable {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ModelSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ModelSpec"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}model_id\0\u{3}model_path\0\u{3}model_kind\0\u{1}revision\0\u{3}tokenizer_hash\0\u{3}quant_profile_id\0\u{3}parser_mode\0\u{3}reasoning_mode\0\u{3}max_context\0\u{1}ext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.modelID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.modelPath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.modelKind) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.revision) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.tokenizerHash) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.quantProfileID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.parserMode) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.reasoningMode) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.maxContext) }()
      case 10: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.ext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.modelID.isEmpty {
      try visitor.visitSingularStringField(value: self.modelID, fieldNumber: 1)
    }
    if !self.modelPath.isEmpty {
      try visitor.visitSingularStringField(value: self.modelPath, fieldNumber: 2)
    }
    if !self.modelKind.isEmpty {
      try visitor.visitSingularStringField(value: self.modelKind, fieldNumber: 3)
    }
    if !self.revision.isEmpty {
      try visitor.visitSingularStringField(value: self.revision, fieldNumber: 4)
    }
    if !self.tokenizerHash.isEmpty {
      try visitor.visitSingularStringField(value: self.tokenizerHash, fieldNumber: 5)
    }
    if !self.quantProfileID.isEmpty {
      try visitor.visitSingularStringField(value: self.quantProfileID, fieldNumber: 6)
    }
    if !self.parserMode.isEmpty {
      try visitor.visitSingularStringField(value: self.parserMode, fieldNumber: 7)
    }
    if !self.reasoningMode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasoningMode, fieldNumber: 8)
    }
    if self.maxContext != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxContext, fieldNumber: 9)
    }
    if !self.ext.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.ext, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ModelSpec, rhs: Melix_Worker_V1_ModelSpec) -> Bool {
    if lhs.modelID != rhs.modelID {return false}
    if lhs.modelPath != rhs.modelPath {return false}
    if lhs.modelKind != rhs.modelKind {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.tokenizerHash != rhs.tokenizerHash {return false}
    if lhs.quantProfileID != rhs.quantProfileID {return false}
    if lhs.parserMode != rhs.parserMode {return false}
    if lhs.reasoningMode != rhs.reasoningMode {return false}
    if lhs.maxContext != rhs.maxContext {return false}
    if lhs.ext != rhs.ext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_RuntimeCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RuntimeCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}cache\0\u{1}execution\0\u{1}parsing\0\u{1}multimodal\0\u{1}ext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._cache) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._execution) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._parsing) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._multimodal) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.ext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._cache {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._execution {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._parsing {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._multimodal {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.ext.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ext, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_RuntimeCapabilities, rhs: Melix_Worker_V1_RuntimeCapabilities) -> Bool {
    if lhs._cache != rhs._cache {return false}
    if lhs._execution != rhs._execution {return false}
    if lhs._parsing != rhs._parsing {return false}
    if lhs._multimodal != rhs._multimodal {return false}
    if lhs.ext != rhs.ext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_CacheCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CacheCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supports_prefix_cache\0\u{3}supports_paged_cache\0\u{3}supports_disk_cache\0\u{3}kv_quant_profiles\0\u{3}supports_boundary_snapshots\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.supportsPrefixCache) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.supportsPagedCache) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.supportsDiskCache) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.kvQuantProfiles) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.supportsBoundarySnapshots) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.supportsPrefixCache != false {
      try visitor.visitSingularBoolField(value: self.supportsPrefixCache, fieldNumber: 1)
    }
    if self.supportsPagedCache != false {
      try visitor.visitSingularBoolField(value: self.supportsPagedCache, fieldNumber: 2)
    }
    if self.supportsDiskCache != false {
      try visitor.visitSingularBoolField(value: self.supportsDiskCache, fieldNumber: 3)
    }
    if !self.kvQuantProfiles.isEmpty {
      try visitor.visitRepeatedStringField(value: self.kvQuantProfiles, fieldNumber: 4)
    }
    if self.supportsBoundarySnapshots != false {
      try visitor.visitSingularBoolField(value: self.supportsBoundarySnapshots, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_CacheCapabilities, rhs: Melix_Worker_V1_CacheCapabilities) -> Bool {
    if lhs.supportsPrefixCache != rhs.supportsPrefixCache {return false}
    if lhs.supportsPagedCache != rhs.supportsPagedCache {return false}
    if lhs.supportsDiskCache != rhs.supportsDiskCache {return false}
    if lhs.kvQuantProfiles != rhs.kvQuantProfiles {return false}
    if lhs.supportsBoundarySnapshots != rhs.supportsBoundarySnapshots {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ExecutionCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExecutionCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supports_continuous_batching\0\u{3}supports_speculative_decoding\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.supportsContinuousBatching) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.supportsSpeculativeDecoding) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.supportsContinuousBatching != false {
      try visitor.visitSingularBoolField(value: self.supportsContinuousBatching, fieldNumber: 1)
    }
    if self.supportsSpeculativeDecoding != false {
      try visitor.visitSingularBoolField(value: self.supportsSpeculativeDecoding, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ExecutionCapabilities, rhs: Melix_Worker_V1_ExecutionCapabilities) -> Bool {
    if lhs.supportsContinuousBatching != rhs.supportsContinuousBatching {return false}
    if lhs.supportsSpeculativeDecoding != rhs.supportsSpeculativeDecoding {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ParserCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ParserCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supports_tool_call_auto_parsing\0\u{3}supports_reasoning_separation\0\u{3}supported_tool_parsers\0\u{3}supported_reasoning_parsers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.supportsToolCallAutoParsing) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.supportsReasoningSeparation) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.supportedToolParsers) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.supportedReasoningParsers) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.supportsToolCallAutoParsing != false {
      try visitor.visitSingularBoolField(value: self.supportsToolCallAutoParsing, fieldNumber: 1)
    }
    if self.supportsReasoningSeparation != false {
      try visitor.visitSingularBoolField(value: self.supportsReasoningSeparation, fieldNumber: 2)
    }
    if !self.supportedToolParsers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.supportedToolParsers, fieldNumber: 3)
    }
    if !self.supportedReasoningParsers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.supportedReasoningParsers, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ParserCapabilities, rhs: Melix_Worker_V1_ParserCapabilities) -> Bool {
    if lhs.supportsToolCallAutoParsing != rhs.supportsToolCallAutoParsing {return false}
    if lhs.supportsReasoningSeparation != rhs.supportsReasoningSeparation {return false}
    if lhs.supportedToolParsers != rhs.supportedToolParsers {return false}
    if lhs.supportedReasoningParsers != rhs.supportedReasoningParsers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_MultimodalCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MultimodalCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}supports_vision\0\u{3}supports_audio\0\u{3}supports_image_generation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.supportsVision) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.supportsAudio) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.supportsImageGeneration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.supportsVision != false {
      try visitor.visitSingularBoolField(value: self.supportsVision, fieldNumber: 1)
    }
    if self.supportsAudio != false {
      try visitor.visitSingularBoolField(value: self.supportsAudio, fieldNumber: 2)
    }
    if self.supportsImageGeneration != false {
      try visitor.visitSingularBoolField(value: self.supportsImageGeneration, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_MultimodalCapabilities, rhs: Melix_Worker_V1_MultimodalCapabilities) -> Bool {
    if lhs.supportsVision != rhs.supportsVision {return false}
    if lhs.supportsAudio != rhs.supportsAudio {return false}
    if lhs.supportsImageGeneration != rhs.supportsImageGeneration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_Capability: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Capability"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.metadata.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadata, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_Capability, rhs: Melix_Worker_V1_Capability) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_CacheScope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CacheScope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}model_id\0\u{1}revision\0\u{3}tokenizer_hash\0\u{3}quant_profile_id\0\u{3}prompt_template_hash\0\u{3}parser_mode\0\u{3}reasoning_mode\0\u{3}multimodal_adapter_hash\0\u{3}scope_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.modelID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.revision) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.tokenizerHash) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.quantProfileID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.promptTemplateHash) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.parserMode) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.reasoningMode) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.multimodalAdapterHash) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.scopeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.modelID.isEmpty {
      try visitor.visitSingularStringField(value: self.modelID, fieldNumber: 1)
    }
    if !self.revision.isEmpty {
      try visitor.visitSingularStringField(value: self.revision, fieldNumber: 2)
    }
    if !self.tokenizerHash.isEmpty {
      try visitor.visitSingularStringField(value: self.tokenizerHash, fieldNumber: 3)
    }
    if !self.quantProfileID.isEmpty {
      try visitor.visitSingularStringField(value: self.quantProfileID, fieldNumber: 4)
    }
    if !self.promptTemplateHash.isEmpty {
      try visitor.visitSingularStringField(value: self.promptTemplateHash, fieldNumber: 5)
    }
    if !self.parserMode.isEmpty {
      try visitor.visitSingularStringField(value: self.parserMode, fieldNumber: 6)
    }
    if !self.reasoningMode.isEmpty {
      try visitor.visitSingularStringField(value: self.reasoningMode, fieldNumber: 7)
    }
    if !self.multimodalAdapterHash.isEmpty {
      try visitor.visitSingularStringField(value: self.multimodalAdapterHash, fieldNumber: 8)
    }
    if !self.scopeID.isEmpty {
      try visitor.visitSingularStringField(value: self.scopeID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_CacheScope, rhs: Melix_Worker_V1_CacheScope) -> Bool {
    if lhs.modelID != rhs.modelID {return false}
    if lhs.revision != rhs.revision {return false}
    if lhs.tokenizerHash != rhs.tokenizerHash {return false}
    if lhs.quantProfileID != rhs.quantProfileID {return false}
    if lhs.promptTemplateHash != rhs.promptTemplateHash {return false}
    if lhs.parserMode != rhs.parserMode {return false}
    if lhs.reasoningMode != rhs.reasoningMode {return false}
    if lhs.multimodalAdapterHash != rhs.multimodalAdapterHash {return false}
    if lhs.scopeID != rhs.scopeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_CacheKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CacheKey"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prefix_hash\0\u{3}fingerprint_hash\0\u{3}scope_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.prefixHash) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.fingerprintHash) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.scopeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.prefixHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.prefixHash, fieldNumber: 1)
    }
    if !self.fingerprintHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.fingerprintHash, fieldNumber: 2)
    }
    if !self.scopeID.isEmpty {
      try visitor.visitSingularStringField(value: self.scopeID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_CacheKey, rhs: Melix_Worker_V1_CacheKey) -> Bool {
    if lhs.prefixHash != rhs.prefixHash {return false}
    if lhs.fingerprintHash != rhs.fingerprintHash {return false}
    if lhs.scopeID != rhs.scopeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_PrefixRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PrefixRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}prefix_id\0\u{3}cache_key\0\u{1}scope\0\u{3}token_length\0\u{1}pinned\0\u{1}tier\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.prefixID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._cacheKey) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.tokenLength) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.pinned) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.tier) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.prefixID.isEmpty {
      try visitor.visitSingularStringField(value: self.prefixID, fieldNumber: 1)
    }
    try { if let v = self._cacheKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.tokenLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenLength, fieldNumber: 4)
    }
    if self.pinned != false {
      try visitor.visitSingularBoolField(value: self.pinned, fieldNumber: 5)
    }
    if !self.tier.isEmpty {
      try visitor.visitSingularStringField(value: self.tier, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_PrefixRef, rhs: Melix_Worker_V1_PrefixRef) -> Bool {
    if lhs.prefixID != rhs.prefixID {return false}
    if lhs._cacheKey != rhs._cacheKey {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.tokenLength != rhs.tokenLength {return false}
    if lhs.pinned != rhs.pinned {return false}
    if lhs.tier != rhs.tier {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_SnapshotRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SnapshotRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}snapshot_id\0\u{3}request_id\0\u{3}session_id\0\u{3}branch_id\0\u{3}token_boundary\0\u{3}checkpoint_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.snapshotID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.branchID) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.tokenBoundary) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.checkpointID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.snapshotID.isEmpty {
      try visitor.visitSingularStringField(value: self.snapshotID, fieldNumber: 1)
    }
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 2)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 3)
    }
    if !self.branchID.isEmpty {
      try visitor.visitSingularStringField(value: self.branchID, fieldNumber: 4)
    }
    if self.tokenBoundary != 0 {
      try visitor.visitSingularUInt32Field(value: self.tokenBoundary, fieldNumber: 5)
    }
    if !self.checkpointID.isEmpty {
      try visitor.visitSingularStringField(value: self.checkpointID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_SnapshotRef, rhs: Melix_Worker_V1_SnapshotRef) -> Bool {
    if lhs.snapshotID != rhs.snapshotID {return false}
    if lhs.requestID != rhs.requestID {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.branchID != rhs.branchID {return false}
    if lhs.tokenBoundary != rhs.tokenBoundary {return false}
    if lhs.checkpointID != rhs.checkpointID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_SamplingConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SamplingConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}temperature\0\u{3}top_p\0\u{3}top_k\0\u{3}frequency_penalty\0\u{3}presence_penalty\0\u{3}max_output_tokens\0\u{1}stop\0\u{1}seed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.temperature) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.topP) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.topK) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.frequencyPenalty) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.presencePenalty) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.maxOutputTokens) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.stop) }()
      case 8: try { try decoder.decodeSingularUInt32Field(value: &self.seed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.temperature.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperature, fieldNumber: 1)
    }
    if self.topP.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.topP, fieldNumber: 2)
    }
    if self.topK != 0 {
      try visitor.visitSingularUInt32Field(value: self.topK, fieldNumber: 3)
    }
    if self.frequencyPenalty.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.frequencyPenalty, fieldNumber: 4)
    }
    if self.presencePenalty.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.presencePenalty, fieldNumber: 5)
    }
    if self.maxOutputTokens != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxOutputTokens, fieldNumber: 6)
    }
    if !self.stop.isEmpty {
      try visitor.visitRepeatedStringField(value: self.stop, fieldNumber: 7)
    }
    if self.seed != 0 {
      try visitor.visitSingularUInt32Field(value: self.seed, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_SamplingConfig, rhs: Melix_Worker_V1_SamplingConfig) -> Bool {
    if lhs.temperature != rhs.temperature {return false}
    if lhs.topP != rhs.topP {return false}
    if lhs.topK != rhs.topK {return false}
    if lhs.frequencyPenalty != rhs.frequencyPenalty {return false}
    if lhs.presencePenalty != rhs.presencePenalty {return false}
    if lhs.maxOutputTokens != rhs.maxOutputTokens {return false}
    if lhs.stop != rhs.stop {return false}
    if lhs.seed != rhs.seed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ReasoningConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReasoningConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}enabled\0\u{1}parser\0\u{3}separate_stream\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enabled) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.parser) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.separateStream) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enabled != false {
      try visitor.visitSingularBoolField(value: self.enabled, fieldNumber: 1)
    }
    if !self.parser.isEmpty {
      try visitor.visitSingularStringField(value: self.parser, fieldNumber: 2)
    }
    if self.separateStream != false {
      try visitor.visitSingularBoolField(value: self.separateStream, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ReasoningConfig, rhs: Melix_Worker_V1_ReasoningConfig) -> Bool {
    if lhs.enabled != rhs.enabled {return false}
    if lhs.parser != rhs.parser {return false}
    if lhs.separateStream != rhs.separateStream {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ToolDefinition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ToolDefinition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}description\0\u{3}json_schema\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.jsonSchema) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 2)
    }
    if !self.jsonSchema.isEmpty {
      try visitor.visitSingularStringField(value: self.jsonSchema, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ToolDefinition, rhs: Melix_Worker_V1_ToolDefinition) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.jsonSchema != rhs.jsonSchema {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ToolConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ToolConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}tools\0\u{3}schema_format\0\u{3}schema_version\0\u{3}toolset_version\0\u{1}parser\0\u{3}parser_contract_version\0\u{3}tool_choice\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.tools) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.schemaFormat) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.schemaVersion) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.toolsetVersion) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.parser) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.parserContractVersion) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.toolChoice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.tools.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tools, fieldNumber: 1)
    }
    if !self.schemaFormat.isEmpty {
      try visitor.visitSingularStringField(value: self.schemaFormat, fieldNumber: 2)
    }
    if !self.schemaVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.schemaVersion, fieldNumber: 3)
    }
    if !self.toolsetVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.toolsetVersion, fieldNumber: 4)
    }
    if !self.parser.isEmpty {
      try visitor.visitSingularStringField(value: self.parser, fieldNumber: 5)
    }
    if !self.parserContractVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.parserContractVersion, fieldNumber: 6)
    }
    if !self.toolChoice.isEmpty {
      try visitor.visitSingularStringField(value: self.toolChoice, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ToolConfig, rhs: Melix_Worker_V1_ToolConfig) -> Bool {
    if lhs.tools != rhs.tools {return false}
    if lhs.schemaFormat != rhs.schemaFormat {return false}
    if lhs.schemaVersion != rhs.schemaVersion {return false}
    if lhs.toolsetVersion != rhs.toolsetVersion {return false}
    if lhs.parser != rhs.parser {return false}
    if lhs.parserContractVersion != rhs.parserContractVersion {return false}
    if lhs.toolChoice != rhs.toolChoice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_MessagePart: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessagePart"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}image_uri\0\u{3}image_bytes\0\u{3}audio_uri\0\u{3}audio_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.part != nil {try decoder.handleConflictingOneOf()}
          self.part = .text(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.part != nil {try decoder.handleConflictingOneOf()}
          self.part = .imageUri(v)
        }
      }()
      case 3: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.part != nil {try decoder.handleConflictingOneOf()}
          self.part = .imageBytes(v)
        }
      }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.part != nil {try decoder.handleConflictingOneOf()}
          self.part = .audioUri(v)
        }
      }()
      case 5: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.part != nil {try decoder.handleConflictingOneOf()}
          self.part = .audioBytes(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.part {
    case .text?: try {
      guard case .text(let v)? = self.part else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .imageUri?: try {
      guard case .imageUri(let v)? = self.part else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .imageBytes?: try {
      guard case .imageBytes(let v)? = self.part else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 3)
    }()
    case .audioUri?: try {
      guard case .audioUri(let v)? = self.part else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case .audioBytes?: try {
      guard case .audioBytes(let v)? = self.part else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_MessagePart, rhs: Melix_Worker_V1_MessagePart) -> Bool {
    if lhs.part != rhs.part {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_ChatMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}role\0\u{1}name\0\u{1}parts\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.role) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.parts) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.role.isEmpty {
      try visitor.visitSingularStringField(value: self.role, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.parts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.parts, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_ChatMessage, rhs: Melix_Worker_V1_ChatMessage) -> Bool {
    if lhs.role != rhs.role {return false}
    if lhs.name != rhs.name {return false}
    if lhs.parts != rhs.parts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_CacheHints: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CacheHints"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}allow_l1\0\u{3}allow_l2\0\u{3}persist_l2\0\u{3}prefer_hot_prefix\0\u{3}save_boundary_snapshot\0\u{3}restore_snapshot_id\0\u{3}pin_prefix_ids\0\u{3}cache_policy\0\u{3}preferred_block_size\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.allowL1) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.allowL2) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.persistL2) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.preferHotPrefix) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.saveBoundarySnapshot) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.restoreSnapshotID) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.pinPrefixIds) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.cachePolicy) }()
      case 9: try { try decoder.decodeSingularUInt32Field(value: &self.preferredBlockSize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.allowL1 != false {
      try visitor.visitSingularBoolField(value: self.allowL1, fieldNumber: 1)
    }
    if self.allowL2 != false {
      try visitor.visitSingularBoolField(value: self.allowL2, fieldNumber: 2)
    }
    if self.persistL2 != false {
      try visitor.visitSingularBoolField(value: self.persistL2, fieldNumber: 3)
    }
    if self.preferHotPrefix != false {
      try visitor.visitSingularBoolField(value: self.preferHotPrefix, fieldNumber: 4)
    }
    if self.saveBoundarySnapshot != false {
      try visitor.visitSingularBoolField(value: self.saveBoundarySnapshot, fieldNumber: 5)
    }
    if !self.restoreSnapshotID.isEmpty {
      try visitor.visitSingularStringField(value: self.restoreSnapshotID, fieldNumber: 6)
    }
    if !self.pinPrefixIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.pinPrefixIds, fieldNumber: 7)
    }
    if !self.cachePolicy.isEmpty {
      try visitor.visitSingularStringField(value: self.cachePolicy, fieldNumber: 8)
    }
    if self.preferredBlockSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.preferredBlockSize, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_CacheHints, rhs: Melix_Worker_V1_CacheHints) -> Bool {
    if lhs.allowL1 != rhs.allowL1 {return false}
    if lhs.allowL2 != rhs.allowL2 {return false}
    if lhs.persistL2 != rhs.persistL2 {return false}
    if lhs.preferHotPrefix != rhs.preferHotPrefix {return false}
    if lhs.saveBoundarySnapshot != rhs.saveBoundarySnapshot {return false}
    if lhs.restoreSnapshotID != rhs.restoreSnapshotID {return false}
    if lhs.pinPrefixIds != rhs.pinPrefixIds {return false}
    if lhs.cachePolicy != rhs.cachePolicy {return false}
    if lhs.preferredBlockSize != rhs.preferredBlockSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_RequestIdentity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RequestIdentity"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}session_id\0\u{3}branch_id\0\u{3}parent_request_id\0\u{3}workflow_run_id\0\u{3}workflow_node_id\0\u{3}latency_class\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.branchID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.parentRequestID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.workflowRunID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.workflowNodeID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.latencyClass) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 2)
    }
    if !self.branchID.isEmpty {
      try visitor.visitSingularStringField(value: self.branchID, fieldNumber: 3)
    }
    if !self.parentRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.parentRequestID, fieldNumber: 4)
    }
    if !self.workflowRunID.isEmpty {
      try visitor.visitSingularStringField(value: self.workflowRunID, fieldNumber: 5)
    }
    if !self.workflowNodeID.isEmpty {
      try visitor.visitSingularStringField(value: self.workflowNodeID, fieldNumber: 6)
    }
    if !self.latencyClass.isEmpty {
      try visitor.visitSingularStringField(value: self.latencyClass, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_RequestIdentity, rhs: Melix_Worker_V1_RequestIdentity) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.branchID != rhs.branchID {return false}
    if lhs.parentRequestID != rhs.parentRequestID {return false}
    if lhs.workflowRunID != rhs.workflowRunID {return false}
    if lhs.workflowNodeID != rhs.workflowNodeID {return false}
    if lhs.latencyClass != rhs.latencyClass {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_SchedulingHints: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SchedulingHints"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}priority\0\u{1}lane\0\u{3}latency_sensitive\0\u{3}queue_delay_ms\0\u{3}queue_position\0\u{3}admission_policy\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.priority) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.lane) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.latencySensitive) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.queueDelayMs) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.queuePosition) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.admissionPolicy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.priority != 0 {
      try visitor.visitSingularInt32Field(value: self.priority, fieldNumber: 1)
    }
    if !self.lane.isEmpty {
      try visitor.visitSingularStringField(value: self.lane, fieldNumber: 2)
    }
    if self.latencySensitive != false {
      try visitor.visitSingularBoolField(value: self.latencySensitive, fieldNumber: 3)
    }
    if self.queueDelayMs != 0 {
      try visitor.visitSingularUInt32Field(value: self.queueDelayMs, fieldNumber: 4)
    }
    if self.queuePosition != 0 {
      try visitor.visitSingularUInt32Field(value: self.queuePosition, fieldNumber: 5)
    }
    if !self.admissionPolicy.isEmpty {
      try visitor.visitSingularStringField(value: self.admissionPolicy, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_SchedulingHints, rhs: Melix_Worker_V1_SchedulingHints) -> Bool {
    if lhs.priority != rhs.priority {return false}
    if lhs.lane != rhs.lane {return false}
    if lhs.latencySensitive != rhs.latencySensitive {return false}
    if lhs.queueDelayMs != rhs.queueDelayMs {return false}
    if lhs.queuePosition != rhs.queuePosition {return false}
    if lhs.admissionPolicy != rhs.admissionPolicy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_AccelerationPolicy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccelerationPolicy"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mode\0\u{3}profile_id\0\u{3}draft_model_id\0\u{3}prefill_hint\0\u{3}active_kv_quant_profile\0\u{3}allow_baseline_fallback\0\u{1}ext\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.mode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.profileID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.draftModelID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.prefillHint) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.activeKvQuantProfile) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.allowBaselineFallback) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.ext) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.mode != .unspecified {
      try visitor.visitSingularEnumField(value: self.mode, fieldNumber: 1)
    }
    if !self.profileID.isEmpty {
      try visitor.visitSingularStringField(value: self.profileID, fieldNumber: 2)
    }
    if !self.draftModelID.isEmpty {
      try visitor.visitSingularStringField(value: self.draftModelID, fieldNumber: 3)
    }
    if !self.prefillHint.isEmpty {
      try visitor.visitSingularStringField(value: self.prefillHint, fieldNumber: 4)
    }
    if !self.activeKvQuantProfile.isEmpty {
      try visitor.visitSingularStringField(value: self.activeKvQuantProfile, fieldNumber: 5)
    }
    if self.allowBaselineFallback != false {
      try visitor.visitSingularBoolField(value: self.allowBaselineFallback, fieldNumber: 6)
    }
    if !self.ext.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.ext, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_AccelerationPolicy, rhs: Melix_Worker_V1_AccelerationPolicy) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.profileID != rhs.profileID {return false}
    if lhs.draftModelID != rhs.draftModelID {return false}
    if lhs.prefillHint != rhs.prefillHint {return false}
    if lhs.activeKvQuantProfile != rhs.activeKvQuantProfile {return false}
    if lhs.allowBaselineFallback != rhs.allowBaselineFallback {return false}
    if lhs.ext != rhs.ext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_BlockTable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BlockTable"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}blocks\0\u{3}cache_key\0\u{3}scope_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.blocks) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._cacheKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.scopeID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.blocks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.blocks, fieldNumber: 1)
    }
    try { if let v = self._cacheKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.scopeID.isEmpty {
      try visitor.visitSingularStringField(value: self.scopeID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_BlockTable, rhs: Melix_Worker_V1_BlockTable) -> Bool {
    if lhs.blocks != rhs.blocks {return false}
    if lhs._cacheKey != rhs._cacheKey {return false}
    if lhs.scopeID != rhs.scopeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Melix_Worker_V1_BlockRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BlockRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}block_id\0\u{3}token_start\0\u{3}token_end\0\u{1}bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.blockID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.tokenStart) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.tokenEnd) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.bytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.blockID.isEmpty {
      try visitor.visitSingularStringField(value: self.blockID, fieldNumber: 1)
    }
    if self.tokenStart != 0 {
      try visitor.visitSingularInt32Field(value: self.tokenStart, fieldNumber: 2)
    }
    if self.tokenEnd != 0 {
      try visitor.visitSingularInt32Field(value: self.tokenEnd, fieldNumber: 3)
    }
    if self.bytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.bytes, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Melix_Worker_V1_BlockRef, rhs: Melix_Worker_V1_BlockRef) -> Bool {
    if lhs.blockID != rhs.blockID {return false}
    if lhs.tokenStart != rhs.tokenStart {return false}
    if lhs.tokenEnd != rhs.tokenEnd {return false}
    if lhs.bytes != rhs.bytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
