// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: worker/v1/tool_runtime.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - melix.worker.v1.ToolRuntimeService

/// Namespace containing generated types for the "melix.worker.v1.ToolRuntimeService" service.
@available(macOS 15.0, *)
public enum Melix_Worker_V1_ToolRuntimeService: Sendable {
    /// Service descriptor for the "melix.worker.v1.ToolRuntimeService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "ListAgentTools" metadata.
        public enum ListAgentTools: Sendable {
            /// Request type for "ListAgentTools".
            public typealias Input = Melix_Worker_V1_ListAgentToolsRequest
            /// Response type for "ListAgentTools".
            public typealias Output = Melix_Worker_V1_ToolCatalogReceipt
            /// Descriptor for "ListAgentTools".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService"),
                method: "ListAgentTools",
                type: .unary
            )
        }
        /// Namespace for "ExecuteAgentTool" metadata.
        public enum ExecuteAgentTool: Sendable {
            /// Request type for "ExecuteAgentTool".
            public typealias Input = Melix_Worker_V1_ExecuteAgentToolRequest
            /// Response type for "ExecuteAgentTool".
            public typealias Output = Melix_Worker_V1_AgentToolExecutionEvent
            /// Descriptor for "ExecuteAgentTool".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService"),
                method: "ExecuteAgentTool",
                type: .serverStreaming
            )
        }
        /// Namespace for "CancelAgentTool" metadata.
        public enum CancelAgentTool: Sendable {
            /// Request type for "CancelAgentTool".
            public typealias Input = Melix_Worker_V1_CancelAgentToolRequest
            /// Response type for "CancelAgentTool".
            public typealias Output = Melix_Worker_V1_CancelAgentToolResponse
            /// Descriptor for "CancelAgentTool".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService"),
                method: "CancelAgentTool",
                type: .unary
            )
        }
        /// Namespace for "CancelAgentRunTools" metadata.
        public enum CancelAgentRunTools: Sendable {
            /// Request type for "CancelAgentRunTools".
            public typealias Input = Melix_Worker_V1_CancelAgentRunToolsRequest
            /// Response type for "CancelAgentRunTools".
            public typealias Output = Melix_Worker_V1_CancelAgentRunToolsResponse
            /// Descriptor for "CancelAgentRunTools".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService"),
                method: "CancelAgentRunTools",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "melix.worker.v1.ToolRuntimeService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            ListAgentTools.descriptor,
            ExecuteAgentTool.descriptor,
            CancelAgentTool.descriptor,
            CancelAgentRunTools.descriptor
        ]
    }
}

@available(macOS 15.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "melix.worker.v1.ToolRuntimeService" service.
    public static let melix_worker_v1_ToolRuntimeService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "melix.worker.v1.ToolRuntimeService")
}

// MARK: melix.worker.v1.ToolRuntimeService (server)

@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService {
    /// Streaming variant of the service protocol for the "melix.worker.v1.ToolRuntimeService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "ListAgentTools" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_ListAgentToolsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_ToolCatalogReceipt` messages.
        func listAgentTools(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_ListAgentToolsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_ToolCatalogReceipt>

        /// Handle the "ExecuteAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_ExecuteAgentToolRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_AgentToolExecutionEvent` messages.
        func executeAgentTool(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_AgentToolExecutionEvent>

        /// Handle the "CancelAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_CancelAgentToolRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_CancelAgentToolResponse` messages.
        func cancelAgentTool(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_CancelAgentToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_CancelAgentToolResponse>

        /// Handle the "CancelAgentRunTools" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Melix_Worker_V1_CancelAgentRunToolsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_CancelAgentRunToolsResponse` messages.
        func cancelAgentRunTools(
            request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>
    }

    /// Service protocol for the "melix.worker.v1.ToolRuntimeService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Melix_Worker_V1_ToolRuntimeService.StreamingServiceProtocol {
        /// Handle the "ListAgentTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ListAgentToolsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_ToolCatalogReceipt` message.
        func listAgentTools(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_ListAgentToolsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_ToolCatalogReceipt>

        /// Handle the "ExecuteAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ExecuteAgentToolRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Melix_Worker_V1_AgentToolExecutionEvent` messages.
        func executeAgentTool(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_AgentToolExecutionEvent>

        /// Handle the "CancelAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentToolRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_CancelAgentToolResponse` message.
        func cancelAgentTool(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_CancelAgentToolRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentToolResponse>

        /// Handle the "CancelAgentRunTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentRunToolsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Melix_Worker_V1_CancelAgentRunToolsResponse` message.
        func cancelAgentRunTools(
            request: GRPCCore.ServerRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>
    }

    /// Simple service protocol for the "melix.worker.v1.ToolRuntimeService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Melix_Worker_V1_ToolRuntimeService.ServiceProtocol {
        /// Handle the "ListAgentTools" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_ListAgentToolsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_ToolCatalogReceipt` to respond with.
        func listAgentTools(
            request: Melix_Worker_V1_ListAgentToolsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_ToolCatalogReceipt

        /// Handle the "ExecuteAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_ExecuteAgentToolRequest` message.
        ///   - response: A response stream of `Melix_Worker_V1_AgentToolExecutionEvent` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func executeAgentTool(
            request: Melix_Worker_V1_ExecuteAgentToolRequest,
            response: GRPCCore.RPCWriter<Melix_Worker_V1_AgentToolExecutionEvent>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "CancelAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_CancelAgentToolRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_CancelAgentToolResponse` to respond with.
        func cancelAgentTool(
            request: Melix_Worker_V1_CancelAgentToolRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_CancelAgentToolResponse

        /// Handle the "CancelAgentRunTools" method.
        ///
        /// - Parameters:
        ///   - request: A `Melix_Worker_V1_CancelAgentRunToolsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Melix_Worker_V1_CancelAgentRunToolsResponse` to respond with.
        func cancelAgentRunTools(
            request: Melix_Worker_V1_CancelAgentRunToolsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Melix_Worker_V1_CancelAgentRunToolsResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Melix_Worker_V1_ToolRuntimeService.Method.ListAgentTools.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_ListAgentToolsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_ToolCatalogReceipt>(),
            handler: { request, context in
                try await self.listAgentTools(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_ToolRuntimeService.Method.ExecuteAgentTool.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_ExecuteAgentToolRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_AgentToolExecutionEvent>(),
            handler: { request, context in
                try await self.executeAgentTool(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_ToolRuntimeService.Method.CancelAgentTool.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_CancelAgentToolRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_CancelAgentToolResponse>(),
            handler: { request, context in
                try await self.cancelAgentTool(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Melix_Worker_V1_ToolRuntimeService.Method.CancelAgentRunTools.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_CancelAgentRunToolsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_CancelAgentRunToolsResponse>(),
            handler: { request, context in
                try await self.cancelAgentRunTools(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService.ServiceProtocol {
    public func listAgentTools(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_ListAgentToolsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_ToolCatalogReceipt> {
        let response = try await self.listAgentTools(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func executeAgentTool(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_AgentToolExecutionEvent> {
        let response = try await self.executeAgentTool(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func cancelAgentTool(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_CancelAgentToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_CancelAgentToolResponse> {
        let response = try await self.cancelAgentTool(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func cancelAgentRunTools(
        request: GRPCCore.StreamingServerRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_CancelAgentRunToolsResponse> {
        let response = try await self.cancelAgentRunTools(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService.SimpleServiceProtocol {
    public func listAgentTools(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_ListAgentToolsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_ToolCatalogReceipt> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_ToolCatalogReceipt>(
            message: try await self.listAgentTools(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func executeAgentTool(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Melix_Worker_V1_AgentToolExecutionEvent> {
        return GRPCCore.StreamingServerResponse<Melix_Worker_V1_AgentToolExecutionEvent>(
            metadata: [:],
            producer: { writer in
                try await self.executeAgentTool(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func cancelAgentTool(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_CancelAgentToolRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentToolResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentToolResponse>(
            message: try await self.cancelAgentTool(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func cancelAgentRunTools(
        request: GRPCCore.ServerRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentRunToolsResponse> {
        return GRPCCore.ServerResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>(
            message: try await self.cancelAgentRunTools(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: melix.worker.v1.ToolRuntimeService (client)

@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService {
    /// Generated client protocol for the "melix.worker.v1.ToolRuntimeService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "ListAgentTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ListAgentToolsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_ListAgentToolsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_ToolCatalogReceipt` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listAgentTools<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_ListAgentToolsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_ListAgentToolsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_ToolCatalogReceipt>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_ToolCatalogReceipt>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ExecuteAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ExecuteAgentToolRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_ExecuteAgentToolRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_AgentToolExecutionEvent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func executeAgentTool<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_ExecuteAgentToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_AgentToolExecutionEvent>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Melix_Worker_V1_AgentToolExecutionEvent>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CancelAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentToolRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_CancelAgentToolRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_CancelAgentToolResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func cancelAgentTool<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_CancelAgentToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_CancelAgentToolResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentToolResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CancelAgentRunTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentRunToolsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_CancelAgentRunToolsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_CancelAgentRunToolsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func cancelAgentRunTools<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_CancelAgentRunToolsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "melix.worker.v1.ToolRuntimeService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "ListAgentTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ListAgentToolsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_ListAgentToolsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_ToolCatalogReceipt` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listAgentTools<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_ListAgentToolsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_ListAgentToolsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_ToolCatalogReceipt>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_ToolCatalogReceipt>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_ToolRuntimeService.Method.ListAgentTools.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ExecuteAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_ExecuteAgentToolRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_ExecuteAgentToolRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_AgentToolExecutionEvent` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func executeAgentTool<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_ExecuteAgentToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_AgentToolExecutionEvent>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Melix_Worker_V1_AgentToolExecutionEvent>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Melix_Worker_V1_ToolRuntimeService.Method.ExecuteAgentTool.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CancelAgentTool" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentToolRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_CancelAgentToolRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_CancelAgentToolResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func cancelAgentTool<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentToolRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_CancelAgentToolRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_CancelAgentToolResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentToolResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_ToolRuntimeService.Method.CancelAgentTool.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CancelAgentRunTools" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentRunToolsRequest` message.
        ///   - serializer: A serializer for `Melix_Worker_V1_CancelAgentRunToolsRequest` messages.
        ///   - deserializer: A deserializer for `Melix_Worker_V1_CancelAgentRunToolsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func cancelAgentRunTools<Result>(
            request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            serializer: some GRPCCore.MessageSerializer<Melix_Worker_V1_CancelAgentRunToolsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Melix_Worker_V1_CancelAgentRunToolsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Melix_Worker_V1_ToolRuntimeService.Method.CancelAgentRunTools.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService.ClientProtocol {
    /// Call the "ListAgentTools" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_ListAgentToolsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listAgentTools<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_ListAgentToolsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_ToolCatalogReceipt>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listAgentTools(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_ListAgentToolsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_ToolCatalogReceipt>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ExecuteAgentTool" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_ExecuteAgentToolRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func executeAgentTool<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_ExecuteAgentToolRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Melix_Worker_V1_AgentToolExecutionEvent>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.executeAgentTool(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_ExecuteAgentToolRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_AgentToolExecutionEvent>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelAgentTool" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentToolRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelAgentTool<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentToolRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentToolResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.cancelAgentTool(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_CancelAgentToolRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_CancelAgentToolResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelAgentRunTools" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Melix_Worker_V1_CancelAgentRunToolsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelAgentRunTools<Result>(
        request: GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.cancelAgentRunTools(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Melix_Worker_V1_CancelAgentRunToolsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Melix_Worker_V1_CancelAgentRunToolsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, *)
extension Melix_Worker_V1_ToolRuntimeService.ClientProtocol {
    /// Call the "ListAgentTools" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listAgentTools<Result>(
        _ message: Melix_Worker_V1_ListAgentToolsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_ToolCatalogReceipt>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_ListAgentToolsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listAgentTools(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ExecuteAgentTool" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func executeAgentTool<Result>(
        _ message: Melix_Worker_V1_ExecuteAgentToolRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Melix_Worker_V1_AgentToolExecutionEvent>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_ExecuteAgentToolRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.executeAgentTool(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelAgentTool" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelAgentTool<Result>(
        _ message: Melix_Worker_V1_CancelAgentToolRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentToolResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentToolRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.cancelAgentTool(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelAgentRunTools" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelAgentRunTools<Result>(
        _ message: Melix_Worker_V1_CancelAgentRunToolsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Melix_Worker_V1_CancelAgentRunToolsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Melix_Worker_V1_CancelAgentRunToolsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.cancelAgentRunTools(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}